export default {
    USER_WITH_THIS_EMAIL_DOES_NOT_EXIST: 'USER_WITH_THIS_EMAIL_DOES_NOT_EXIST',
    EMAIL_SHOULD_NOT_BE_EMPTY: 'EMAIL_SHOULD_NOT_BE_EMPTY',
    EMAIL_MUST_BE_AN_EMAIL: 'EMAIL_MUST_BE_AN_EMAIL',
    PASSWORD_SHOULD_NOT_BE_EMPTY: 'PASSWORD_SHOULD_NOT_BE_EMPTY',
    WRONG_PASSWORD: 'WRONG_PASSWORD'
};