export default {
  CLOSE_CIRCLE: 'close-circle' as const,
  EYE: 'eye' as const,
  EYE_OFF: 'eye-off' as const,
  CHEVRON_DOWN: 'chevron-down' as const,
  CHEVRON_UP: 'chevron-up' as const,
  CHEVRON_FORWARD_OUTLINE: 'chevron-forward-outline' as const,
  CALENDAR: 'calendar' as const,
  PERSON_OUTLINE: 'person-outline' as const,
  HOME_OUTLINE: 'home-outline' as const,
  LOG_OUT_OUTLINE: 'log-out-outline' as const,
  ADD_OUTLINE: 'add-outline' as const,
  PAW_OUTLINE: 'paw-outline' as const,
  FITNESS_OUTLINE: 'fitness-outline' as const,
  BUSINESS_OUTLINE: 'business-outline' as const,
  MEDKIT_OUTLINE: 'medkit-outline' as const,
  CHECKMARK_OUTLINE: 'checkmark-outline' as const,
  PENCIL_OUTLINE: 'pencil-outline' as const,
  TIME_OUTLINE: 'time-outline' as const,
  TRASH_OUTLINE: 'trash-outline' as const,
};
